### PR TITLE
HA: 0.91 -> 0.93

### PR DESCRIPTION
**Pull request by nickw444**
* Upgrade to 0.93
* Enable mobile app beta support

### CODE REVIEW

**Comment by nickw444** [comment]
Appears to be an issue with syncthru: 
image

Most likely due to https://github.com/home-assistant/home-assistant/pull/21482

**Comment by Lefuneste83** [comment]
I have also noticed that the latest version of syncthru from the 24th of April makes the toner level unreadable with a Samsung ML-2950 (status "Unknown"). I have applied the previous version from the 12th of April as a custom_component and the toner level appears again. Must be some kind of regression. The printer is detected by the discovery function.
I have checked my pysyncthru version : it is indeed 0.4.2. The regression is likely due to modifications in sensor.py
"https://github.com/home-assistant/home-assistant/commits/dev/homeassistant/components/syncthru"

**Comment by cflev** [comment]
Same problem here on "M262x 282x Series"

**Comment by nickw444** [comment]
> Same problem here on "M262x 282x Series"

Please file a bug report with home-assistant: https://github.com/home-assistant/home-assistant/issues/new/choose

**Pull request closed without merging**
